# Use the official Node.js image as the base image
FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the application dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Need to build to get entity.js files inside dist folder
# Since migration will need these instead of entity.ts files
RUN npm run build

# Expose the application port
EXPOSE 3000

# Command to run the application
# CMD npm run migration:generate -- migrations/Init && npm run start:dev
CMD ["npm", "run", "start:dev"]
