services:
  db:
    image: mysql
    container_name: dcube-teachers-db
    restart: always
    networks:
      - dcube-teachers-network
    env_file:
      - .env/.mysql.env
    healthcheck:
      test: "mysql $$MYSQL_DATABASE -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1;'"
      interval: 20s
      timeout: 10s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dcube-teachers-api
    restart: always
    networks:
      - dcube-teachers-network
    env_file:
      - .env/.env
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - NODE_ENV=development
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    depends_on:
      db:
        condition: service_healthy
        restart: true

networks:
  dcube-teachers-network:
