version: '3'

services:
  db:
    image: mysql
    restart: always
    networks:
      - dcube-teachers-network
    env_file:
      - .env.dev

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    networks:
      - dcube-teachers-network
    env_file:
      - .env.dev
    environment:
      - DB_HOST=db
      - DB_PORT=3306
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

networks:
  dcube-teachers-network:
