name: Build and deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.AWS_EC2_SSH_KEY }}
      HOST: ${{ secrets.AWS_EC2_HOST }}
      USER: ${{ secrets.AWS_EC2_USER }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Write SSH PEM
        run: echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem

      - name: Create env file and copy to EC2
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          # cat .env
          ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} "mkdir -p env"
          scp -o StrictHostKeyChecking=no -i github-ec2.pem .env ${USER}@${HOST}:~/env

      - name: Clone or pull github repo
        run: |
          ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} '
          
          REPO_URL="https://github.com/trungnd3/dcube-teachers.git"

          if [ -d "$HOME/dcube-teachers/.git" ]; then
            cd $HOME/dcube-teachers
            git pull origin main
          else
            git clone $REPO_URL
            cd $HOME/dcube-teachers
          fi
          '

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} '

          cp $HOME/env/.env $HOME/dcube-teachers
          cd $HOME/dcube-teachers
          docker build -t dcube-teachers .
          docker container stop dcube-teachers
          docker container rm dcube-teachers
          docker run --name dcube-teachers -d --env-file .env -p 443:3000 dcube-teachers
          '
