name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Workload Identity Federation
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-actions@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"

      - name: Configure gcloud CLI
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud auth list

      - name: Build docker image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/nest-app .

      - name: Push the image to ECR
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/nest-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.GCP_CLOUD_RUN_SERVICE }} \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/nest-app \
            --platform managed \
            --region asia-southeast1 \
            --allow-unauthenticated \
            --add-cloudsql-instances=${{ secrets.INSTANCE_CONNECTION_NAME }}
            --set-env-vars "DB_USER=${{ secrets.DB_USER }},DB_PASSWORD=${{ secrets.DB_PASSWORD }},DB_DATABASE=${{ secrets.DB_DATABASE }},INSTANCE_CONNECTION_PATH=/cloudsql/${{ secrets.INSTANCE_CONNECTION_NAME }}"
