name: Build and deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.AWS_EC2_SSH_KEY }}
      HOST: ${{ secrets.AWS_EC2_HOST }}
      USER: ${{ secrets.AWS_EC2_USER }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Authenticate to ECR
        run : aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REPO_URI }}

      - name: Build docker image
        run: docker build -t manguardian/dcube-teachers .

      - name: Tag docker image
        run: docker tag manguardian/dcube-teachers:latest ${{ secrets.AWS_ECR_REPO_URI }}:latest

      - name: Push the image to ECR
        run: docker push ${{ secrets.AWS_ECR_REPO_URI }}:latest
